name: build and push images

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - { postgres: 14 }
          - { postgres: 15 }
          - { postgres: 16 }
          - { postgres: 17 }
          - { postgres: 18 }

    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write

    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      build-args: |
        PG_MAJOR=${{ matrix.postgres }}
      meta-images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      meta-tags: |
        type=raw,value=${{ matrix.postgres }}

    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
